---
title: "The Probability of Ties"
author: "Abhay Paidipalli"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

**This study determines the probability that two groups have the same exact average value of a characteristic.**

<br>

In this scenario, there are two people, A and B, who are each rolling a multi-faced die, with $s$ number of sides, $t$ number of times. Each face of the die is assigned a value from 1 to $s$ and all of the faces have an equal chance of being rolled. After the rolls are conducted, the average value per roll is determined. What is the probability that A and B have the exact same average?

<br>

Through computer simulations, a relationship between $s$, the number of sides on the multi-faced die, and $t$, the number of times the die is rolled, was obtained. The relationship is as follows: $$P(s, t) = \frac{1}{s\sqrt{t}}$$ Where $P$ represents the probability of A and B having the same average value per roll considering that both people have a die with $s$ number of faces and roll it $t$ number of times.

_____________________________________________________________________________

P(sides = 2, rolls = 1)

Set of possible average values: [1, 2]

<br>

A --> Rolling a sum of 1 -->   1   --> $1 * \frac{1}{2}$

A --> Rolling a sum of 2 -->   2   --> $1 * \frac{1}{2}$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{2}^{2} + \frac{1}{2}^{2} = \frac{1}{4} + \frac{1}{4} = \frac{1}{2}$$

Probability using obtained formula: $$P(s = 2, t = 1) = \frac{1}{2\sqrt{1}} = \frac{1}{2}$$

_____________________________________________________________________________

P(sides = 2, rolls = 2)

Set of possible average values: [1, 1.5, 2]

<br>

A --> Rolling a sum of 2 -->   1  1             --> $1 * (\frac{1}{2})(\frac{1}{2})$

A --> Rolling a sum of 3 -->   1  2  ||  2  1   --> $2 * (\frac{1}{2})(\frac{1}{2})$

A --> Rolling a sum of 4 -->   2  2             --> $1 * (\frac{1}{2})(\frac{1}{2})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{4}^{2} + \frac{2}{4}^{2} + \frac{1}{4}^{2} = \frac{1}{16} + \frac{4}{16} + \frac{1}{16} = \frac{6}{16} = \frac{3}{8}$$

Probability using obtained formula: $$P(s = 2, t = 2) = \frac{1}{2\sqrt{2}}$$

_____________________________________________________________________________

P(sides = 2, rolls = 3)

Set of possible average values: [1, 1.33, 1.67, 2]

<br>

A --> Rolling a sum of 3 -->   1  1  1         --> $1 * (\frac{1}{2})(\frac{1}{2})(\frac{1}{2})$

A --> Rolling a sum of 4 -->   1  2  1  (x3)   --> $3 * (\frac{1}{2})(\frac{1}{2})(\frac{1}{2})$

A --> Rolling a sum of 5 -->   2  2  1  (x3)   --> $3 * (\frac{1}{2})(\frac{1}{2})(\frac{1}{2})$

A --> Rolling a sum of 6 -->   2  2  2         --> $1 * (\frac{1}{2})(\frac{1}{2})(\frac{1}{2})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{8}^{2} + \frac{3}{8}^{2} + \frac{3}{8}^{2} + \frac{1}{8}^{2} = \frac{1}{64} + \frac{9}{64} + \frac{9}{64} + \frac{1}{64} = \frac{20}{64} = \frac{5}{16}$$

Probability using obtained formula: $$P(s = 2, t = 3) = \frac{1}{2\sqrt{3}}$$

_____________________________________________________________________________

P(sides = 3, rolls = 1)

Set of possible average values: [1, 2, 3]

<br>

A --> Rolling a sum of 1 -->   1   --> $1 * \frac{1}{3}$

A --> Rolling a sum of 2 -->   2   --> $1 * \frac{1}{3}$

A --> Rolling a sum of 3 -->   3   --> $1 * \frac{1}{3}$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{3}^{2} + \frac{1}{3}^{2} + \frac{1}{3}^{2} = \frac{1}{9} + \frac{1}{9} + \frac{1}{9} = \frac{1}{3}$$

Probability using obtained formula: $$P(s = 3, t = 1) = \frac{1}{3\sqrt{1}} = \frac{1}{3}$$

_____________________________________________________________________________

P(sides = 3, rolls = 2)

Set of possible average values: [1, 1.5, 2, 2.5, 3]

<br>

A --> Rolling a sum of 2 -->   1  1                       --> $1 * (\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 3 -->   1  2  ||  2  1             --> $2 * (\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 4 -->   1  3  ||  2  2  ||  3  1   --> $3 * (\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 5 -->   2  3  ||  3  2             --> $2 * (\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 6 -->   3  3                       --> $1 * (\frac{1}{3})(\frac{1}{3})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{9}^{2} + \frac{2}{9}^{2} + \frac{3}{9}^{2} + \frac{2}{9}^{2} + \frac{1}{9}^{2} = \frac{1}{81} + \frac{4}{81} + \frac{9}{81} + \frac{4}{81} + \frac{1}{81} = \frac{19}{81}$$

Probability using obtained formula: $$P(s = 3, t = 2) = \frac{1}{3\sqrt{2}}$$

_____________________________________________________________________________

P(sides = 3, rolls = 3)

Set of possible average values: [1, 1.33, 1.67, 2, 2.33, 2.67, 3]

<br>

A --> Rolling a sum of 3 -->   1  1  1                            --> $1 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 4 -->   1  1  2  (x3)                      --> $3 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 5 -->   1  2  2  (x3)  ||  1  1  3  (x3)   --> $6 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 6 -->   2  2  2  ||  1  2  3  (x6)         --> $7 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 7 -->   2  2  3  (x3)  ||  1  3  3  (x3)   --> $6 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 8 -->   2  3  3  (x3)                      --> $3 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 9 -->   3  3  3                            --> $1 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{27}^{2} + \frac{3}{27}^{2} + \frac{6}{27}^{2} + \frac{7}{27}^{2} + \frac{6}{27}^{2} + \frac{3}{27}^{2} + \frac{1}{27}^{2} = \frac{1}{729} + \frac{9}{729} + \frac{36}{729} + \frac{49}{729} + \frac{36}{729} + \frac{9}{729} + \frac{1}{729} = \frac{141}{729} = \frac{47}{243}$$

Probability using obtained formula: $$P(s = 3, t = 3) = \frac{1}{3\sqrt{3}}$$

_____________________________________________________________________________

P(sides = 3, rolls = 4)

Set of possible average values: [1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75, 3]

<br>

A --> Rolling a sum of 4 -->   1  1  1  1                                                --> $1 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 5 -->   1  1  1  2  (x4)                                          --> $4 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 6 -->   1  1  2  2  (x6)  ||  1  1  1  3  (x4)                    --> $10 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 7 -->   1  2  2  2  (x4)  ||  1  1  2  3  (x12)                   --> $16 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 8 -->   2  2  2  2  ||  1  1  3  3  (x6)  ||  1  2  2  3  (x12)   --> $19 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 9 -->   2  2  2  3  (x4)  ||  1  2  3  3  (x12)                   --> $16 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 10 -->   2  2  3  3  (x6)  ||  1  3  3  3  (x4)                   --> $10 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 11 -->   2  3  3  3  (x4)                                         --> $4 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

A --> Rolling a sum of 12 -->   3  3  3  3                                               --> $1 * (\frac{1}{3})(\frac{1}{3})(\frac{1}{3})(\frac{1}{3})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{81}^{2} + \frac{4}{81}^{2} + \frac{10}{81}^{2} + \frac{16}{81}^{2} + \frac{19}{81}^{2} + \frac{16}{81}^{2} + \frac{10}{81}^{2} + \frac{4}{81}^{2} + \frac{1}{81}^{2} = \frac{1}{6561} + \frac{16}{6561} + \frac{100}{6561} + \frac{256}{6561} + \frac{361}{6561} + \frac{256}{6561} + \frac{100}{6561} + \frac{16}{6561} + \frac{1}{6561} = \frac{1107}{6561} = \frac{41}{243}$$

Probability using obtained formula: $$P(s = 3, t = 4) = \frac{1}{3\sqrt{4}} = \frac{1}{6}$$

_____________________________________________________________________________

P(sides = 4, rolls = 1)

Set of possible average values: [1, 2, 3, 4]

<br>

A --> Rolling a sum of 1 -->   1   --> $1 * (\frac{1}{4})$

A --> Rolling a sum of 2 -->   2   --> $1 * (\frac{1}{4})$

A --> Rolling a sum of 3 -->   3   --> $1 * (\frac{1}{4})$

A --> Rolling a sum of 4 -->   4   --> $1 * (\frac{1}{4})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{4}^{2} + \frac{1}{4}^{2} + \frac{1}{4}^{2} + \frac{1}{4}^{2} = \frac{1}{16} + \frac{1}{16} + \frac{1}{16} + \frac{1}{16} = \frac{4}{16} = \frac{1}{4}$$

Probability using obtained formula: $$P(s = 4, t = 1) = \frac{1}{4\sqrt{1}} = \frac{1}{4}$$

_____________________________________________________________________________

P(sides = 4, rolls = 2)

Set of possible average values: [1, 1.5, 2, 2.5, 3, 3.5, 4]

<br>

A --> Rolling a sum of 2 -->   1  1                         --> $1 * (\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 3 -->   1  2  (x2)                   --> $2 * (\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 4 -->   1  3  (x2)  ||  2  2         --> $3 * (\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 5 -->   1  4  (x2)  ||  2  3  (x2)   --> $4 * (\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 6 -->   2  4  (x2)  ||  3  3         --> $3 * (\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 7 -->   3  4  (x2)                   --> $2 * (\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 8 -->   4  4                         --> $1 * (\frac{1}{4})(\frac{1}{4})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{16}^{2} + \frac{2}{16}^{2} + \frac{3}{16}^{2} + \frac{4}{16}^{2} + \frac{3}{16}^{2} + \frac{2}{16}^{2} + \frac{1}{16}^{2} = \frac{1}{256} + \frac{4}{256} + \frac{9}{256} + \frac{16}{256} + \frac{9}{256} + \frac{4}{256} + \frac{1}{256} = \frac{44}{256} = \frac{11}{64}$$

Probability using obtained formula: $$P(s = 4, t = 2) = \frac{1}{4\sqrt{2}}$$

_____________________________________________________________________________

P(sides = 4, rolls = 3)

Set of possible average values: [1, 1.33, 1.67, 2, 2.33, 2.67, 3, 3.33, 3.67, 4]

<br>

A --> Rolling a sum of 3 -->   1  1  1   --> $1 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 4 -->   1  1  2  (x3)   --> $3 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 5 -->   1  2  2  (x3)  ||  1  1  3  (x3)   --> $6 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 6 -->   2  2  2  ||  1  2  3  (x6)  ||  1  1  4  (x3)   --> $10 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 7 -->   2  2  3  (x3)  ||  1  3  3  (x3)  ||  1  2  4  (x6)   --> $12 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 8 -->   2  3  3  (x3)  ||  1  3  4  (x6)  ||  2  2  4  (x3)   --> $12 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 9 -->   3  3  3  ||  2  3  4  (x6)  ||  1  4  4  (x3)   --> $10 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 10 -->   3  3  4  (x3)  ||  2  4  4  (x3)   --> $6 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 11 -->   3  4  4  (x3)   --> $3 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

A --> Rolling a sum of 12 -->   4  4  4   --> $1 * (\frac{1}{4})(\frac{1}{4})(\frac{1}{4})$

<br>

Since B is rolling an identical die the same number of times as A, the probabilities for each of the aforementioned possibilities are the same; therefore, the probability of A and B having a tie is:

$$\frac{1}{64}^{2} + \frac{3}{64}^{2} + \frac{6}{64}^{2} + \frac{10}{64}^{2} + \frac{12}{64}^{2} + \frac{12}{64}^{2} + \frac{10}{64}^{2} + \frac{6}{64}^{2} + \frac{3}{64}^{2} + \frac{1}{64}^{2} = \frac{1}{4096} + \frac{9}{4096} + \frac{36}{4096} + \frac{100}{4096} + \frac{144}{4096} + \frac{144}{4096} + \frac{100}{4096} + \frac{36}{4096} + \frac{9}{4096} + \frac{1}{4096} = \frac{580}{4096} = \frac{145}{1024}$$

Probability using obtained formula: $$P(s = 4, t = 3) = \frac{1}{4\sqrt{3}}$$

_____________________________________________________________________________

After observing the outcomes of the examples above, it is reasonable to assume that the mathematics involved here utilize an application of the binomial theorem, in which the binomial coefficient is defined by:

$$\binom{n}{k} = \frac{n!}{k!(n-k)!}$$

<br>


P(sides = 2, rolls = 1)
$$\overbrace{\frac{1}{2}^{2}}^{1} + \overbrace{\frac{1}{2}^{2}}^{2}$$
P(sides = 2, rolls = 2)
$$\overbrace{\frac{1}{4}^{2}}^{1} + \overbrace{\frac{2}{4}^{2}}^{1.5} + \overbrace{\frac{1}{4}^{2}}^{2}$$
P(sides = 2, rolls = 3)
$$\overbrace{\frac{1}{8}^{2}}^{1} + \overbrace{\frac{3}{8}^{2}}^{1.33} + \overbrace{\frac{3}{8}^{2}}^{1.67} + \overbrace{\frac{1}{8}^{2}}^{2}$$
P(sides = 3, rolls = 1)
$$\overbrace{\frac{1}{3}^{2}}^{1} + \overbrace{\frac{1}{3}^{2}}^{2} + \overbrace{\frac{1}{3}^{2}}^{3}$$
P(sides = 3, rolls = 2)
$$\overbrace{\frac{1}{9}^{2}}^{1} + \overbrace{\frac{2}{9}^{2}}^{1.5} + \overbrace{\frac{3}{9}^{2}}^{2} + \overbrace{\frac{2}{9}^{2}}^{2.5} + \overbrace{\frac{1}{9}^{2}}^{3}$$
P(sides = 3, rolls = 3)
$$\overbrace{\frac{1}{27}^{2}}^{1} + \overbrace{\frac{3}{27}^{2}}^{1.33} + \overbrace{\frac{6}{27}^{2}}^{1.67} + \overbrace{\frac{7}{27}^{2}}^{2} + \overbrace{\frac{6}{27}^{2}}^{2.33} + \overbrace{\frac{3}{27}^{2}}^{2.67} + \overbrace{\frac{1}{27}^{2}}^{3}$$
P(sides = 3, rolls = 4)
$$\overbrace{\frac{1}{81}^{2}}^{1} + \overbrace{\frac{4}{81}^{2}}^{1.25} + \overbrace{\frac{10}{81}^{2}}^{1.5} + \overbrace{\frac{16}{81}^{2}}^{1.75} + \overbrace{\frac{19}{81}^{2}}^{2} + \overbrace{\frac{16}{81}^{2}}^{2.25} + \overbrace{\frac{10}{81}^{2}}^{2.5} + \overbrace{\frac{4}{81}^{2}}^{2.75} + \overbrace{\frac{1}{81}^{2}}^{3}$$
P(sides = 4, rolls = 1)
$$\overbrace{\frac{1}{4}^{2}}^{1} + \overbrace{\frac{1}{4}^{2}}^{2} + \overbrace{\frac{1}{4}^{2}}^{3} + \overbrace{\frac{1}{4}^{2}}^{4}$$
P(sides = 4, rolls = 2)
$$\overbrace{\frac{1}{16}^{2}}^{1} + \overbrace{\frac{2}{16}^{2}}^{1.5} + \overbrace{\frac{3}{16}^{2}}^{2} + \overbrace{\frac{4}{16}^{2}}^{2.5} + \overbrace{\frac{3}{16}^{2}}^{3} + \overbrace{\frac{2}{16}^{2}}^{3.5} + \overbrace{\frac{1}{16}^{2}}^{4}$$
P(sides = 4, rolls = 3)
$$\overbrace{\frac{1}{64}^{2}}^{1} + \overbrace{\frac{3}{64}^{2}}^{1.33} + \overbrace{\frac{6}{64}^{2}}^{1.67} + \overbrace{\frac{10}{64}^{2}}^{2} + \overbrace{\frac{12}{64}^{2}}^{2.33} + \overbrace{\frac{12}{64}^{2}}^{2.67} + \overbrace{\frac{10}{64}^{2}}^{3} + \overbrace{\frac{6}{64}^{2}}^{3.33} + \overbrace{\frac{3}{64}^{2}}^{3.67} + \overbrace{\frac{1}{64}^{2}}^{4}$$

<br>

Denominator will always be: $N^{2x}$

<br>

<br>








